#!/bin/bash
echo ' setHook("rstudio.sessionInit", function(newSession) {              ' >  .Rprofile
echo '   if (newSession){                                                 ' >> .Rprofile
echo '     if( is.null(rstudioapi::getActiveProject()) ){                 ' >> .Rprofile
echo '     rstudioapi::openProject("/home/rstudio/fischerRRR-manuscript") ' >> .Rprofile
echo '   }                                                                ' >> .Rprofile
echo '                                                                    ' >> .Rprofile
echo '                                                                    ' >> .Rprofile
echo ' }                                                                  ' >> .Rprofile
echo '   if(rstudioapi::getActiveProject() == "/home/jovyan/my_rproject"){' >> .Rprofile
echo '     #rstudioapi::navigateToFile("README.md")                       ' >> .Rprofile
echo '   }                                                                ' >> .Rprofile
echo ' }, action = "append")                                              ' >> .Rprofile
